// <auto-generated />
using System;
using GloEpidBot.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GloEpidBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GloEpidBot.Model.Domain.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Age = 25,
                            DateReported = new DateTime(2020, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cooperative Villas, Ajah",
                            ReporterName = "Kenny",
                            RiskStatus = "High",
                            Symptoms = "I have been experiencing sever cough and headache"
                        },
                        new
                        {
                            Id = 101,
                            Age = 50,
                            DateReported = new DateTime(2020, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cooperative Villas, Ajah",
                            ReporterName = "Teju",
                            RiskStatus = "High",
                            Symptoms = "cough and difficulty in breathing"
                        },
                        new
                        {
                            Id = 102,
                            Age = 70,
                            DateReported = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cooperative Villas, Ajah",
                            ReporterName = "Kenny",
                            RiskStatus = "low",
                            Symptoms = "None"
                        },
                        new
                        {
                            Id = 103,
                            Age = 30,
                            DateReported = new DateTime(2020, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cooperative Villas, Ajah",
                            ReporterName = "Kenny",
                            RiskStatus = "low",
                            Symptoms = "None"
                        },
                        new
                        {
                            Id = 4,
                            Age = 80,
                            DateReported = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cooperative Villas, Ajah",
                            ReporterName = "Tega",
                            RiskStatus = "High",
                            Symptoms = "sever cough and headache"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
